title: <p align="center"> Piyali Podder</p>
logo: /assets/img/Piyali.jpeg
 
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="linkedin.com/in/piyali-podder-610b78175">LinkedIn</a> |
  <a href="https://github.com/PtechSvy">GitHub</a>
  </p>



theme: jekyll-theme-minimal
