title: <p align="center"> Piyali Podder </p>
logo: /assets/img/Piyali.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="linkedin.com/in/piyali-podder-610b78175">LinkedIn</a> |
  <a href="https://github.com/PtechSvy">GitHub</a>
  
  <br>   
  I'm working on Automation Testing projects related to UI and API frameworks and also I work as DevOps Associate for deploying changes to different environment
  and also on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
